language: go
sudo: false
go:
- "1.14"

addons:
  apt:
    packages:
      - rpm
script:
- make test
- make
#before_deploy:
#- make
#- gem install fpm && make packages
#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key: ${GITHUB_TOKEN}
#  file_glob: true
#  file: "*.{deb,rpm}"
#  on:
#    repo: msaf1980/godownloader
#    tags: true
